# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Workflow

on:
  pull_request:
    branches: master
    types: closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build files
        run: CI='' npm run build
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: build/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: built-files
          path: build/
          
      - name: Move build files to repos build folder
        run: |
          mv build/* build/
        working-directory: ${{ github.workspace }}
